import { lazy, Suspense, useEffect, useMemo, useState } from 'react';
import { getManufactureAddresses, type ManufactureAddress } from '../../services/manufactureAddresses';
const CobeGlobe = lazy(() => import('../ui/CobeGlobe'));

type FulfillmentItem = { id: string; partNumber: string; description: string; requested: number; delivered: number; unitPrice: number };
type Request = { id: string; number: string; customer: string; createdAt: string; needDate: string; status: string; total: number; attachment?: string; items: FulfillmentItem[]; history: Array<{ status: string; date: string; note: string }> };

const usd = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' });
const shortDate = new Intl.DateTimeFormat('en-US', { month: 'short', day: '2-digit', year: 'numeric' });
const requests: Request[] = [
  { id: 'r1', number: 'WO-2026-00842', customer: 'Foresea', createdAt: '2026-08-18', needDate: '2026-09-18', status: 'In review', total: 128640.5, attachment: 'PO-FORESEA-1842.pdf', items: [{ id: 'i1', partNumber: '2792564', description: 'CABLE, CRE, J-BOX 1 TO AID DPT, GEN 2, 122.00IN', requested: 4, delivered: 0, unitPrice: 1467.38 }, { id: 'i2', partNumber: '2960756', description: 'KIT, BLADDER 10L ACCUMULATOR SUB SEA SERVICE', requested: 3, delivered: 0, unitPrice: 3541.31 }, { id: 'i3', partNumber: '2255468', description: 'ACCUMULATOR HOUSING SEAL, 18.7 50 IN ID', requested: 8, delivered: 0, unitPrice: 1035.83 }], history: [{ status: 'Submitted', date: '2026-08-18T13:42:00', note: 'Purchase request created by customer.' }, { status: 'Commercial validation', date: '2026-08-18T15:05:00', note: 'Pricing and requested quantities validated.' }, { status: 'In review', date: '2026-08-19T10:20:00', note: 'Waiting for fulfillment treatment.' }] },
  { id: 'r2', number: 'WO-2026-00817', customer: 'Constellation', createdAt: '2026-08-12', needDate: '2026-09-04', status: 'Approved', total: 54349.45, items: [{ id: 'i4', partNumber: '1372027', description: 'FLANGE, 21-1/4, 10M LIFT FLANGE WITH SHACKLE', requested: 2, delivered: 0, unitPrice: 54349.45 }, { id: 'i5', partNumber: '2937459', description: 'CABLE, CRE, AID BULKHEAD TO CANISTER, GEN 2', requested: 5, delivered: 0, unitPrice: 3371.85 }], history: [{ status: 'Submitted', date: '2026-08-12T09:12:00', note: 'Purchase request received.' }, { status: 'Approved', date: '2026-08-15T16:10:00', note: 'Commercial approval completed.' }] },
  { id: 'r3', number: 'WO-2026-00791', customer: 'Petrobras', createdAt: '2026-08-03', needDate: '2026-08-30', status: 'Processing', total: 219780, attachment: 'PO-45011287.pdf', items: [{ id: 'i6', partNumber: '2937460', description: 'CABLE, JUMPER, FS BULKHD TO AID BULKHD, 86IN', requested: 12, delivered: 4, unitPrice: 3414.08 }, { id: 'i7', partNumber: '991225', description: 'EYEBOLT, SHOULDERED, 7/8-9 TYPE 2 STYLE B', requested: 20, delivered: 10, unitPrice: 78.68 }], history: [{ status: 'Submitted', date: '2026-08-03T08:30:00', note: 'Request submitted with purchase order.' }, { status: 'Partially delivered', date: '2026-08-16T14:30:00', note: 'First item batch delivered.' }, { status: 'Processing', date: '2026-08-17T09:45:00', note: 'Remaining quantities in preparation.' }] },
];

export default function OrderFulfillmentScreen() {
  const [selectedId, setSelectedId] = useState(requests[0].id);
  const [addresses, setAddresses] = useState<ManufactureAddress[]>([]);
  const [addressId, setAddressId] = useState('');
  const [addressesLoading, setAddressesLoading] = useState(true);
  const [addressesError, setAddressesError] = useState('');
  const [query, setQuery] = useState('');
  const [modal, setModal] = useState<'partial' | 'all' | null>(null);
  const [partial, setPartial] = useState<Record<string, number>>({});
  const [toast, setToast] = useState('');
  const selected = requests.find((request) => request.id === selectedId) || requests[0];
  const selectedAddress = addresses.find((address) => address.id === addressId) || addresses[0];
  const globeMarkers = useMemo(() => addresses.map((address) => ({ id: address.id, location: address.location, label: address.choice })), [addresses]);
  const visible = useMemo(() => requests.filter((request) => `${request.number} ${request.customer}`.toLowerCase().includes(query.toLowerCase())), [query]);
  useEffect(() => { if (!modal) return; document.body.classList.add('weparts-dialog-open'); return () => document.body.classList.remove('weparts-dialog-open'); }, [modal]);
  useEffect(() => {
    let active = true;
    getManufactureAddresses()
      .then((data) => {
        if (!active) return;
        setAddresses(data);
        setAddressId((current) => data.some((address) => address.id === current) ? current : data[0]?.id || '');
        setAddressesError(data.length ? '' : 'No active pickup locations with valid coordinates were found.');
      })
      .catch((error: unknown) => {
        if (!active) return;
        setAddressesError(error instanceof Error ? error.message : 'Unable to load pickup locations.');
      })
      .finally(() => { if (active) setAddressesLoading(false); });
    return () => { active = false; };
  }, []);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 3000); };
  const openPartial = () => { setPartial(Object.fromEntries(selected.items.map((item) => [item.id, remaining(item)]))); setModal('partial'); };
  const remaining = (item: FulfillmentItem) => item.requested - item.delivered;

  return <section className="screen active fulfillment-screen">
    <div className="fulfillment-heading"><div><span className="commerce-kicker">ORDER OPERATIONS</span><h1>Order Fulfillment</h1><p>Review requests, assign a pickup location and register complete or partial delivery.</p></div><div className="fulfillment-heading-stat"><span>{requests.length}</span><p><b>OPEN REQUESTS</b><small>Awaiting operational treatment</small></p></div></div>
    <div className="fulfillment-layout">
      <aside className="fulfillment-queue"><div className="queue-head"><div><span>WORK QUEUE</span><b>Purchase requests</b></div><span>{visible.length}</span></div><div className="queue-search"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search request" /></div><div className="queue-list">{visible.map((request) => <button className={request.id === selectedId ? 'active' : ''} onClick={() => { setSelectedId(request.id); setAddressId(addresses[0]?.id || ''); }} key={request.id}><span className="queue-status-dot"/><div><b>{request.number}</b><span>{request.customer}</span><small>Need {shortDate.format(new Date(`${request.needDate}T12:00:00`))}</small></div><strong>{request.items.length}</strong></button>)}</div></aside>
      <main className="fulfillment-workspace"><div className="fulfillment-request-head"><div><span className="commerce-kicker">SELECTED REQUEST</span><h2>{selected.number}</h2><p>{selected.customer} · Created {shortDate.format(new Date(`${selected.createdAt}T12:00:00`))}</p></div><div><span className="order-status status-in-review"><i />{selected.status}</span><strong>{usd.format(selected.total)}</strong></div></div>
        <div className="fulfillment-summary"><div><small>NEED DATE</small><b>{shortDate.format(new Date(`${selected.needDate}T12:00:00`))}</b></div><div><small>ITEMS</small><b>{selected.items.length} products · {selected.items.reduce((sum,item) => sum + item.requested, 0)} units</b></div><div><small>DELIVERY PROGRESS</small><b>{selected.items.reduce((sum,item) => sum + item.delivered, 0)} units delivered</b></div></div>
        <section className="fulfillment-section"><div className="fulfillment-section-head"><div><span>01</span><p><b>Request files</b><small>Documents attached to this purchase request</small></p></div></div>{selected.attachment ? <button className="fulfillment-file" onClick={() => notify(`${selected.attachment} preview will be enabled with Dataverse.`)}><span><svg viewBox="0 0 24 24"><path d="M7 3h7l4 4v14H7z"/><path d="M14 3v5h5M10 13h5M10 17h4"/></svg></span><p><b>{selected.attachment}</b><small>Purchase order · PDF document</small></p><strong>View file ↗</strong></button> : <div className="fulfillment-no-file">No purchase order attached</div>}</section>
        <section className="fulfillment-section"><div className="fulfillment-section-head"><div><span>02</span><p><b>Requested items</b><small>Products and quantities included in this request</small></p></div><span className="items-total-label">{selected.items.reduce((sum,item) => sum + item.requested,0)} UNITS</span></div><div className="requested-items-list">{selected.items.map((item) => <article key={item.id}><span className="requested-item-mark">{item.partNumber.slice(0,2)}</span><div><small>PN {item.partNumber}</small><b>{item.description}</b><p>{usd.format(item.unitPrice)} per unit</p></div><div><small>REQUESTED</small><b>{item.requested}</b></div><div><small>DELIVERED</small><b>{item.delivered}</b></div><strong>{usd.format(item.unitPrice * item.requested)}</strong></article>)}</div></section>
        <section className="fulfillment-section pickup-section"><div className="fulfillment-section-head"><div><span>03</span><p><b>Pickup address</b><small>Select a location to focus it on the globe</small></p></div><span className="required-label">REQUIRED</span></div>{addressesLoading ? <div className="fulfillment-no-file">Loading pickup locations from Dataverse…</div> : addressesError || !selectedAddress ? <div className="fulfillment-no-file">{addressesError || 'No pickup locations are available.'}</div> : <div className="pickup-experience"><div className="pickup-globe-panel"><Suspense fallback={<div className="globe-loading">Preparing locations…</div>}><CobeGlobe markers={globeMarkers} focusLocation={selectedAddress.location} /></Suspense><div className="globe-location-meta"><span>SELECTED LOCATION</span><b>{selectedAddress.choice}</b><small>{selectedAddress.coordinates}</small></div></div><div className="address-list">{addresses.map((address) => <button className={address.id === addressId ? 'selected' : ''} onClick={() => setAddressId(address.id)} key={address.id}><span className="address-radio"><i /></span><div><small>{address.choice}</small><b>{address.name}</b><p>{[address.street, [address.city, address.state].filter(Boolean).join(', ')].filter(Boolean).join(' · ')}</p></div><strong>{address.id === addressId ? 'SELECTED' : 'VIEW'}</strong></button>)}</div></div>}</section>
        <section className="fulfillment-section"><div className="fulfillment-section-head"><div><span>04</span><p><b>Request history</b><small>A chronological record of every status change</small></p></div></div><div className="fulfillment-history">{selected.history.map((event,index) => <article className={index === selected.history.length - 1 ? 'current' : ''} key={`${event.status}-${event.date}`}><span><i>{index === selected.history.length - 1 ? '●' : '✓'}</i></span><div><div className="history-event-title"><b>{event.status}</b>{index === selected.history.length - 1 ? <em>CURRENT STAGE</em> : null}</div><p>{event.note}</p><small>{new Date(event.date).toLocaleString('en-US',{dateStyle:'medium',timeStyle:'short'})}</small></div></article>)}</div></section>
        <div className="fulfillment-actions"><div><small>SELECTED PICKUP LOCATION</small><b>{selectedAddress?.name || 'Select a valid location'}</b></div><button className="btn btn-secondary" disabled={!selectedAddress} onClick={() => notify('Draft saved locally (mock).')}>Save draft</button><button className="btn fulfillment-partial" disabled={!selectedAddress} onClick={openPartial}>Deliver partially</button><button className="btn btn-primary" disabled={!selectedAddress} onClick={() => setModal('all')}>Deliver everything</button></div>
      </main>
    </div>
    {modal ? <div className="fulfillment-modal-backdrop" onMouseDown={(e) => { if (e.target === e.currentTarget) setModal(null); }}><div className="fulfillment-modal" role="dialog" aria-modal="true"><div className="fulfillment-modal-head"><div><span className="commerce-kicker">{modal === 'partial' ? 'PARTIAL DELIVERY' : 'COMPLETE DELIVERY'}</span><h2>{modal === 'partial' ? 'Choose items and quantities' : 'Deliver the complete request?'}</h2><p>{selected.number} · {selected.customer}</p></div><button onClick={() => setModal(null)}>×</button></div>{modal === 'partial' ? <div className="partial-items">{selected.items.map((item) => <article key={item.id}><div><small>PN {item.partNumber}</small><b>{item.description}</b><p>{remaining(item)} of {item.requested} units remaining</p></div><div className="partial-qty"><button onClick={() => setPartial((value) => ({...value,[item.id]:Math.max(0,(value[item.id]||0)-1)}))}>−</button><input value={partial[item.id] || 0} readOnly/><button onClick={() => setPartial((value) => ({...value,[item.id]:Math.min(remaining(item),(value[item.id]||0)+1)}))}>＋</button></div></article>)}</div> : <div className="deliver-all-confirm"><span>✓</span><h3>{selected.items.reduce((sum,item) => sum + remaining(item),0)} remaining units</h3><p>All remaining quantities across {selected.items.length} products will be marked as delivered from <b>{addresses.find((address) => address.id === addressId)?.name}</b>.</p></div>}<div className="fulfillment-modal-footer"><button className="btn btn-secondary" onClick={() => setModal(null)}>Cancel</button><button className="btn btn-primary" disabled={modal === 'partial' && !Object.values(partial).some(Boolean)} onClick={() => { setModal(null); notify(modal === 'partial' ? 'Partial delivery registered (mock).' : 'Complete delivery registered (mock).'); }}>{modal === 'partial' ? 'Confirm partial delivery' : 'Confirm complete delivery'}</button></div></div></div> : null}
    {toast ? <div className="modern-toast" role="status"><span>✓</span><div><b>Order fulfillment</b><small>{toast}</small></div></div> : null}
  </section>;
}
